### ISSUE TITLE
how this works?

### ISSUE THREAD

**Issue by whoami15** [daveozoalor/laravel-qrcode-ecommerce#1]
how this works?
you provided the installation but how this works?
I register and then all are empty.
no admin user

**Comment by davepartner** [comment]
There is a full video course to this in udemy.

Udemy.com/user/daveozoalor

**Comment by whoami15** [comment]
could you please provide me a link?

**Comment by davepartner** [comment]
https://www.udemy.com/user/daveozoalor/
